"use client";

import { useState } from "react";
import { ArrowLeft, Copy, Check, Download, ShieldCheck, HelpCircle, FileText } from "lucide-react";
import { StructuredDecisionModel } from "@/types/decision";

interface DecisionBriefProps {
  model: StructuredDecisionModel;
  onBack: () => void;
  onUpdateReflection: (rating: string, note: string) => void;
}

const REFLECTION_OPTIONS = [
  "Yes, significantly",
  "A little",
  "Not really",
  "I discovered something new"
];

export default function DecisionBrief({ model, onBack, onUpdateReflection }: DecisionBriefProps) {
  const [copied, setCopied] = useState(false);
  const [rating, setRating] = useState(model.reflection?.thinkingChangedRating || "");
  const [reflectionNote, setReflectionNote] = useState(model.reflection?.thinkingChangedNote || "");
  const [savedReflection, setSavedReflection] = useState(!!model.reflection?.thinkingChangedRating);

  const handleSaveReflection = () => {
    onUpdateReflection(rating, reflectionNote);
    setSavedReflection(true);
  };

  const generateMarkdownBrief = () => {
    return `# DECISION BRIEF: ${model.decision}
Generated by Blind Spot — Thinking Companion

## 1. SUMMARY & CONTEXT
- **Decision:** ${model.decision}
- **Context:** ${model.context || "N/A"}
- **Options Considered:** ${model.options.join(", ")}
- **Core Goals:** ${model.goals.join(", ")}
- **Constraints:** ${model.constraints.join(", ")}

## 2. REVERSIBILITY ANALYSIS
- **Tier:** ${model.reversibility.rating}
- **Assessment:** ${model.reversibility.explanation}
- **Rollback Strategy:** ${model.reversibility.rollbackStrategy}

## 3. KEY ASSUMPTIONS IDENTIFIED
${model.assumptions.map(a => `- **Assumption:** ${a.assumption}\n  *Why it matters:* ${a.whyItMatters}\n  *Question to verify:* ${a.questionToVerify}`).join("\n")}

## 4. EVIDENCE CLASSIFICATION
- **Known Facts:** ${model.evidence.facts.join("; ")}
- **Beliefs Stated as Truth:** ${model.evidence.beliefs.join("; ")}
- **Unverified Assumptions:** ${model.evidence.assumptions.join("; ")}
- **Crucial Needs Verification:** ${model.evidence.needsVerification.join("; ")}

## 5. ALTERNATIVES UNPACKED
${model.alternatives.map(alt => `- **[${alt.type}] ${alt.title}:** ${alt.description} (Tradeoff: ${alt.tradeoff})`).join("\n")}

## 6. STAKEHOLDER MAPPING
${model.stakeholders.map(s => `- **${s.group}:** ${s.impact} (Overlooked factor: ${s.oftenOverlookedAspect})`).join("\n")}

## 7. SECOND-ORDER CONSEQUENCES
${model.consequences.map(c => `- **Branch (${c.decisionBranch}):** Immediate -> ${c.immediate} | 6-12 Months -> ${c.secondary} | Unintended -> ${c.unintended}`).join("\n")}

## 8. PRE-MORTEM (FAILURE MODES)
${model.preMortem.map(pm => `- **Failure Scenario:** ${pm.failureScenario}\n  *Root Cause:* ${pm.rootCauseWhy}\n  *Early Warning Signal:* ${pm.earlyWarningSignal}\n  *Mitigating Action:* ${pm.mitigatingAction}`).join("\n")}

## 9. POTENTIAL BLIND SPOTS
${model.blindSpots.map(b => `- **[${b.category}] ${b.title}:** ${b.whyItMatters}\n  *Unknown:* ${b.whatIsUnknown}\n  *Inquiry:* "${b.questionToExamine}"`).join("\n")}

## 10. QUESTIONS WORTH ANSWERING BEFORE COMMITMENT
${model.questions.map(q => `- Q: ${q.question} ${q.userAnswer ? `\n  *Your reflection:* ${q.userAnswer}` : ""}`).join("\n")}

${rating ? `## 11. REFLECTION ON THINKING\n- **Did thinking change?** ${rating}\n- **Notes:** ${reflectionNote || "None"}\n` : ""}

--------------------------------------------------
YOU DECIDE
The AI thinking partner never makes the decision for you.
--------------------------------------------------
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownBrief());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = generateMarkdownBrief();
    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `decision-brief-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="container" style={{ maxWidth: "900px", margin: "0 auto", paddingBottom: "5rem" }}>
      {/* Top Nav */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "2rem" }}>
        <button
          onClick={onBack}
          style={{
            display: "flex",
            alignItems: "center",
            gap: "0.5rem",
            background: "transparent",
            border: "none",
            color: "var(--muted)",
            cursor: "pointer",
            fontSize: "0.95rem"
          }}
        >
          <ArrowLeft size={16} /> Return to Workspace
        </button>

        <div style={{ display: "flex", gap: "0.75rem" }}>
          <button
            onClick={handleCopy}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "0.5rem",
              background: "var(--surface)",
              color: "var(--foreground)",
              border: "1px solid var(--border)",
              padding: "0.6rem 1.1rem",
              borderRadius: "var(--radius-md)",
              fontSize: "0.9rem",
              cursor: "pointer"
            }}
          >
            {copied ? <Check size={16} color="var(--success)" /> : <Copy size={16} />}
            <span>{copied ? "Copied Markdown" : "Copy Brief"}</span>
          </button>

          <button
            onClick={handleDownload}
            style={{
              display: "flex",
              alignItems: "center",
              gap: "0.5rem",
              background: "var(--surface)",
              color: "var(--foreground)",
              border: "1px solid var(--border)",
              padding: "0.6rem 1.1rem",
              borderRadius: "var(--radius-md)",
              fontSize: "0.9rem",
              cursor: "pointer"
            }}
          >
            <Download size={16} />
            <span>Download .MD</span>
          </button>
        </div>
      </div>

      {/* Title Header */}
      <div
        style={{
          background: "linear-gradient(180deg, var(--surface) 0%, rgba(78, 131, 255, 0.05) 100%)",
          border: "1px solid var(--border)",
          borderRadius: "var(--radius-lg)",
          padding: "2rem 2.5rem",
          marginBottom: "2.5rem"
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", color: "var(--primary)", fontSize: "0.85rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: "0.5rem" }}>
          <FileText size={16} /> Structured Synthesis
        </div>
        <h1 style={{ fontSize: "2.2rem", marginBottom: "1rem", lineHeight: 1.2 }}>
          Decision Brief
        </h1>
        <p style={{ color: "var(--foreground)", fontSize: "1.15rem", fontWeight: 500, marginBottom: "0.5rem" }}>
          {model.decision}
        </p>
        <p style={{ color: "var(--muted)", fontSize: "0.95rem" }}>
          {model.summary}
        </p>
      </div>

      {/* Sections Grid */}
      <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
        
        {/* 1. Context & Baseline */}
        <BriefCard title="1. Context, Options & Stated Goals">
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.5rem" }}>
            <div>
              <div style={{ fontSize: "0.85rem", color: "var(--muted)", fontWeight: 600, textTransform: "uppercase", marginBottom: "0.35rem" }}>Options Considered</div>
              <ul style={{ paddingLeft: "1.2rem", margin: 0, color: "var(--foreground)" }}>
                {model.options.map((opt, i) => <li key={i} style={{ marginBottom: "0.25rem" }}>{opt}</li>)}
              </ul>
            </div>
            <div>
              <div style={{ fontSize: "0.85rem", color: "var(--muted)", fontWeight: 600, textTransform: "uppercase", marginBottom: "0.35rem" }}>Core Goals</div>
              <ul style={{ paddingLeft: "1.2rem", margin: 0, color: "var(--foreground)" }}>
                {model.goals.map((g, i) => <li key={i} style={{ marginBottom: "0.25rem" }}>{g}</li>)}
              </ul>
            </div>
          </div>
        </BriefCard>

        {/* 2. Reversibility */}
        <BriefCard title="2. Reversibility & Rollback Analysis">
          <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.75rem" }}>
            <span style={{
              background: model.reversibility.rating.includes("Easily") ? "rgba(78,255,140,0.15)" : "rgba(255,184,78,0.15)",
              color: model.reversibility.rating.includes("Easily") ? "var(--success)" : "var(--warning)",
              padding: "0.3rem 0.8rem",
              borderRadius: "var(--radius-sm)",
              fontWeight: 600,
              fontSize: "0.9rem"
            }}>
              {model.reversibility.rating}
            </span>
          </div>
          <p style={{ color: "var(--foreground)", marginBottom: "0.75rem", fontSize: "0.95rem" }}>
            {model.reversibility.explanation}
          </p>
          <div style={{ background: "rgba(255,255,255,0.03)", padding: "0.85rem 1rem", borderRadius: "var(--radius-sm)", borderLeft: "3px solid var(--primary)", fontSize: "0.9rem" }}>
            <strong>Rollback Guardrail:</strong> {model.reversibility.rollbackStrategy}
          </div>
        </BriefCard>

        {/* 3. Load-Bearing Assumptions */}
        <BriefCard title="3. Key Assumptions Examined">
          <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
            {model.assumptions.map((a, i) => (
              <div key={i} style={{ borderBottom: i < model.assumptions.length - 1 ? "1px solid var(--border)" : "none", paddingBottom: i < model.assumptions.length - 1 ? "1rem" : 0 }}>
                <div style={{ fontWeight: 600, color: "var(--foreground)", marginBottom: "0.25rem" }}>
                  {a.assumption}
                </div>
                <div style={{ color: "var(--muted)", fontSize: "0.88rem", marginBottom: "0.4rem" }}>
                  <strong>Why load-bearing:</strong> {a.whyItMatters}
                </div>
                <div style={{ color: "var(--primary)", fontSize: "0.88rem" }}>
                  <strong>Probe:</strong> {a.questionToVerify}
                </div>
              </div>
            ))}
          </div>
        </BriefCard>

        {/* 4. Evidence Matrix */}
        <BriefCard title="4. Evidence Lens (Separating Fact from Belief)">
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.25rem" }}>
            <div style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)" }}>
              <div style={{ fontWeight: 600, color: "var(--success)", fontSize: "0.85rem", textTransform: "uppercase", marginBottom: "0.5rem" }}>Known Facts</div>
              <ul style={{ paddingLeft: "1.1rem", margin: 0, fontSize: "0.88rem", color: "var(--muted)" }}>
                {model.evidence.facts.map((f, i) => <li key={i}>{f}</li>)}
              </ul>
            </div>
            <div style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)" }}>
              <div style={{ fontWeight: 600, color: "var(--warning)", fontSize: "0.85rem", textTransform: "uppercase", marginBottom: "0.5rem" }}>Beliefs Stated as Truth</div>
              <ul style={{ paddingLeft: "1.1rem", margin: 0, fontSize: "0.88rem", color: "var(--muted)" }}>
                {model.evidence.beliefs.map((b, i) => <li key={i}>{b}</li>)}
              </ul>
            </div>
            <div style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)" }}>
              <div style={{ fontWeight: 600, color: "var(--primary)", fontSize: "0.85rem", textTransform: "uppercase", marginBottom: "0.5rem" }}>Unexamined Assumptions</div>
              <ul style={{ paddingLeft: "1.1rem", margin: 0, fontSize: "0.88rem", color: "var(--muted)" }}>
                {model.evidence.assumptions.map((a, i) => <li key={i}>{a}</li>)}
              </ul>
            </div>
            <div style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)" }}>
              <div style={{ fontWeight: 600, color: "var(--danger)", fontSize: "0.85rem", textTransform: "uppercase", marginBottom: "0.5rem" }}>Must Be Verified</div>
              <ul style={{ paddingLeft: "1.1rem", margin: 0, fontSize: "0.88rem", color: "var(--muted)" }}>
                {model.evidence.needsVerification.map((v, i) => <li key={i}>{v}</li>)}
              </ul>
            </div>
          </div>
        </BriefCard>

        {/* 5. Alternatives */}
        <BriefCard title="5. High-Leverage Alternatives">
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
            {model.alternatives.map((alt, i) => (
              <div key={i} style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)", border: "1px solid var(--border)" }}>
                <div style={{ fontSize: "0.75rem", textTransform: "uppercase", color: "var(--primary)", fontWeight: 600, marginBottom: "0.25rem" }}>
                  {alt.type}
                </div>
                <div style={{ fontWeight: 600, marginBottom: "0.4rem", color: "var(--foreground)" }}>
                  {alt.title}
                </div>
                <p style={{ color: "var(--muted)", fontSize: "0.85rem", margin: "0 0 0.5rem 0", lineHeight: 1.4 }}>
                  {alt.description}
                </p>
                <div style={{ fontSize: "0.8rem", color: "var(--warning)" }}>
                  <strong>Tradeoff:</strong> {alt.tradeoff}
                </div>
              </div>
            ))}
          </div>
        </BriefCard>

        {/* 6. Stakeholders & Externalities */}
        <BriefCard title="6. Stakeholder Ripple Effects">
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
            {model.stakeholders.map((s, i) => (
              <div key={i} style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)" }}>
                <div style={{ fontWeight: 600, color: "var(--foreground)", marginBottom: "0.25rem" }}>
                  {s.group}
                </div>
                <p style={{ fontSize: "0.85rem", color: "var(--muted)", margin: "0 0 0.4rem 0" }}>
                  {s.impact}
                </p>
                <div style={{ fontSize: "0.8rem", color: "var(--primary)" }}>
                  <strong>Overlooked aspect:</strong> {s.oftenOverlookedAspect}
                </div>
              </div>
            ))}
          </div>
        </BriefCard>

        {/* 7. Pre-Mortem (Failure Scenarios) */}
        <BriefCard title="7. Pre-Mortem: What Could Go Wrong?">
          <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
            {model.preMortem.map((pm, i) => (
              <div key={i} style={{ background: "rgba(255, 78, 78, 0.05)", border: "1px solid rgba(255,78,78,0.2)", borderRadius: "var(--radius-md)", padding: "1.2rem" }}>
                <div style={{ fontWeight: 600, color: "var(--foreground)", marginBottom: "0.4rem" }}>
                  {pm.failureScenario}
                </div>
                <div style={{ fontSize: "0.88rem", color: "var(--muted)", marginBottom: "0.3rem" }}>
                  <strong>Root Cause Vulnerability:</strong> {pm.rootCauseWhy}
                </div>
                <div style={{ fontSize: "0.88rem", color: "var(--warning)", marginBottom: "0.3rem" }}>
                  <strong>Early Warning Signal:</strong> {pm.earlyWarningSignal}
                </div>
                <div style={{ fontSize: "0.88rem", color: "var(--success)" }}>
                  <strong>Proactive Mitigation:</strong> {pm.mitigatingAction}
                </div>
              </div>
            ))}
          </div>
        </BriefCard>

        {/* 8. Questions Answered & Reflections */}
        <BriefCard title="8. Questions Worth Answering">
          <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
            {model.questions.map((q, i) => (
              <div key={i} style={{ background: "rgba(255,255,255,0.02)", padding: "1rem", borderRadius: "var(--radius-sm)" }}>
                <div style={{ fontWeight: 600, color: "var(--foreground)", marginBottom: "0.4rem", display: "flex", alignItems: "center", gap: "0.5rem" }}>
                  <HelpCircle size={16} color="var(--primary)" />
                  <span>{q.question}</span>
                </div>
                {q.userAnswer ? (
                  <div style={{ background: "rgba(78, 131, 255, 0.08)", padding: "0.75rem 1rem", borderRadius: "var(--radius-sm)", borderLeft: "3px solid var(--primary)", fontSize: "0.9rem", color: "var(--foreground)" }}>
                    <strong>Your reflection:</strong> {q.userAnswer}
                  </div>
                ) : (
                  <div style={{ fontSize: "0.85rem", color: "var(--muted)", fontStyle: "italic" }}>
                    Unanswered — revisit this inquiry before finalizing your commitment.
                  </div>
                )}
              </div>
            ))}
          </div>
        </BriefCard>

        {/* 9. Reflection Experience */}
        <div
          style={{
            background: "var(--surface)",
            border: "1px solid var(--border)",
            borderRadius: "var(--radius-lg)",
            padding: "2rem",
            boxShadow: "var(--shadow-md)"
          }}
        >
          <h2 style={{ fontSize: "1.4rem", marginBottom: "0.5rem", display: "flex", alignItems: "center", gap: "0.5rem" }}>
            <ShieldCheck color="var(--primary)" />
            Step 15: Post-Analysis Reflection
          </h2>
          <p style={{ color: "var(--muted)", fontSize: "0.95rem", marginBottom: "1.5rem" }}>
            Did your thinking change through this examination?
          </p>

          <div style={{ display: "flex", flexWrap: "wrap", gap: "0.75rem", marginBottom: "1.5rem" }}>
            {REFLECTION_OPTIONS.map((opt, i) => (
              <button
                key={i}
                type="button"
                onClick={() => setRating(opt)}
                style={{
                  padding: "0.6rem 1.2rem",
                  borderRadius: "var(--radius-xl)",
                  border: rating === opt ? "1px solid var(--primary)" : "1px solid var(--border)",
                  background: rating === opt ? "rgba(78, 131, 255, 0.15)" : "var(--surface-hover)",
                  color: rating === opt ? "#fff" : "var(--muted)",
                  fontWeight: rating === opt ? 600 : 400,
                  fontSize: "0.9rem",
                  cursor: "pointer",
                  transition: "all 0.2s ease"
                }}
              >
                {opt}
              </button>
            ))}
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem", marginBottom: "1.5rem" }}>
            <label style={{ fontSize: "0.95rem", fontWeight: 500 }}>
              What changed in your thinking? (Key realization or shift)
            </label>
            <textarea
              value={reflectionNote}
              onChange={e => setReflectionNote(e.target.value)}
              placeholder="e.g. I realized I was over-optimistic about the schedule, so I will propose a 3-month review clause before committing to a 6-month block..."
              rows={3}
              style={{ width: "100%", resize: "vertical" }}
            />
          </div>

          <button
            onClick={handleSaveReflection}
            style={{
              background: "var(--primary)",
              color: "#fff",
              border: "none",
              padding: "0.75rem 1.5rem",
              borderRadius: "var(--radius-md)",
              fontWeight: 600,
              fontSize: "0.95rem",
              cursor: "pointer"
            }}
          >
            {savedReflection ? "Reflection Saved ✓" : "Record Reflection"}
          </button>
        </div>

        {/* 10. YOU DECIDE MANDATE */}
        <div
          style={{
            background: "linear-gradient(135deg, rgba(78, 131, 255, 0.15) 0%, rgba(20, 20, 26, 0.9) 100%)",
            border: "2px solid var(--primary)",
            borderRadius: "var(--radius-xl)",
            padding: "3rem 2rem",
            textAlign: "center",
            marginTop: "2rem",
            boxShadow: "var(--shadow-glow)"
          }}
        >
          <div style={{ fontSize: "0.9rem", textTransform: "uppercase", letterSpacing: "0.15em", color: "var(--primary)", fontWeight: 700, marginBottom: "0.5rem" }}>
            FINAL VERDICT
          </div>
          <h2 style={{ fontSize: "3.2rem", fontWeight: 800, letterSpacing: "-0.04em", marginBottom: "1rem" }}>
            YOU DECIDE
          </h2>
          <p style={{ color: "var(--foreground)", fontSize: "1.2rem", maxWidth: "600px", margin: "0 auto 1.5rem auto", lineHeight: 1.5 }}>
            The AI has unpacked your blind spots, questioned your assumptions, and stress-tested the downside. 
            <br />
            <strong>The decision is entirely yours to make.</strong>
          </p>
          <div style={{ fontSize: "0.85rem", color: "var(--muted)" }}>
            Blind Spot Principle: AI improves human reasoning; human agency remains sovereign.
          </div>
        </div>

      </div>
    </div>
  );
}

function BriefCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      style={{
        background: "var(--surface)",
        border: "1px solid var(--border)",
        borderRadius: "var(--radius-lg)",
        padding: "1.75rem",
        boxShadow: "var(--shadow-sm)"
      }}
    >
      <h2 style={{ fontSize: "1.25rem", marginBottom: "1.25rem", color: "#ffffff", letterSpacing: "-0.02em" }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
